"""Unit tests for proxy_agent DESTINATION detect/rewrite (no live net / iptables)."""

from __future__ import annotations

import pytest

from types import SimpleNamespace

from proxy_agent.iptables_dest import (
    AZ_PROXY_DPORTS,
    IptablesApplyError,
    apply_iptables_plan,
    detect_proxy_destination,
    invert_iptables_argv,
    is_proxy_installed,
    plan_destination_rewrite,
    rewrite_destination_rules,
)

# iptables-save -t nat style fixture matching AntiZapret proxy.sh
FIXTURE_NAT_SAVE = """\
# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p tcp -m tcp --dport 80 -j DNAT --to-destination 203.0.113.10:50080
-A PREROUTING -p tcp -m tcp --dport 443 -j DNAT --to-destination 203.0.113.10:50443
-A PREROUTING -p tcp -m tcp --dport 504 -j DNAT --to-destination 203.0.113.10:50443
-A PREROUTING -p tcp -m tcp --dport 508 -j DNAT --to-destination 203.0.113.10:50080
-A PREROUTING -p tcp -m tcp --dport 50080 -j DNAT --to-destination 203.0.113.10:50080
-A PREROUTING -p tcp -m tcp --dport 50443 -j DNAT --to-destination 203.0.113.10:50443
-A PREROUTING -p udp -m udp --dport 80 -j DNAT --to-destination 203.0.113.10:50080
-A PREROUTING -p udp -m udp --dport 443 -j DNAT --to-destination 203.0.113.10:50443
-A PREROUTING -p udp -m udp --dport 540 -j DNAT --to-destination 203.0.113.10:51443
-A PREROUTING -p udp -m udp --dport 580 -j DNAT --to-destination 203.0.113.10:51080
-A PREROUTING -p udp -m udp --dport 51080 -j DNAT --to-destination 203.0.113.10:51080
-A PREROUTING -p udp -m udp --dport 51443 -j DNAT --to-destination 203.0.113.10:51443
-A PREROUTING -p udp -m udp --dport 52080 -j DNAT --to-destination 203.0.113.10:51080
-A PREROUTING -p udp -m udp --dport 52443 -j DNAT --to-destination 203.0.113.10:51443
-A POSTROUTING -d 203.0.113.10/32 -j SNAT --to-source 198.51.100.1
COMMIT
"""

FIXTURE_EMPTY = """\
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
"""

FIXTURE_UNRELATED = """\
*nat
-A PREROUTING -p tcp -m tcp --dport 8080 -j DNAT --to-destination 10.0.0.5:8080
-A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
"""


def test_az_proxy_dports_cover_known_set():
    expected = {
        80,
        443,
        504,
        508,
        540,
        580,
        50080,
        50443,
        51080,
        51443,
        52080,
        52443,
    }
    assert expected <= AZ_PROXY_DPORTS


def test_detect_proxy_destination_from_dnat():
    assert detect_proxy_destination(FIXTURE_NAT_SAVE) == "203.0.113.10"


def test_detect_proxy_destination_from_snat_only():
    snat_only = """\
*nat
-A POSTROUTING -d 198.51.100.50/32 -j SNAT --to-source 10.0.0.1
COMMIT
"""
    # SNAT alone is not enough without AZ port DNAT for destination detect of "proxy";
    # but if SNAT -d points at an IP and we have no DNAT, detect may still return that IP
    # when is_proxy_installed uses SNAT heuristic — destination IP from SNAT -d.
    assert detect_proxy_destination(snat_only) == "198.51.100.50"


def test_detect_proxy_destination_empty():
    assert detect_proxy_destination(FIXTURE_EMPTY) is None
    assert detect_proxy_destination(FIXTURE_UNRELATED) is None


def test_is_proxy_installed_true_for_az_dnat():
    assert is_proxy_installed(FIXTURE_NAT_SAVE) is True


def test_is_proxy_installed_false_for_unrelated():
    assert is_proxy_installed(FIXTURE_EMPTY) is False
    assert is_proxy_installed(FIXTURE_UNRELATED) is False


def test_rewrite_destination_rules_replaces_ip():
    rewritten = rewrite_destination_rules(FIXTURE_NAT_SAVE, "203.0.113.10", "203.0.113.99")
    assert "203.0.113.10" not in rewritten
    assert "203.0.113.99:50080" in rewritten
    assert "203.0.113.99:50443" in rewritten
    assert "-d 203.0.113.99/32" in rewritten
    assert detect_proxy_destination(rewritten) == "203.0.113.99"


def test_rewrite_destination_rules_noop_when_missing():
    same = rewrite_destination_rules(FIXTURE_NAT_SAVE, "10.0.0.1", "10.0.0.2")
    assert same == FIXTURE_NAT_SAVE


def test_rewrite_does_not_corrupt_prefix_neighbor_ip():
    """Replacing 10.0.0.1 must leave 10.0.0.10 untouched (IP end-boundary)."""
    rules = """\
*nat
-A PREROUTING -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.0.0.1:50080
-A PREROUTING -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.0.0.10:50443
-A POSTROUTING -d 10.0.0.1/32 -j SNAT --to-source 198.51.100.1
-A POSTROUTING -d 10.0.0.10/32 -j SNAT --to-source 198.51.100.1
COMMIT
"""
    rewritten = rewrite_destination_rules(rules, "10.0.0.1", "10.0.0.2")
    assert "--to-destination 10.0.0.2:50080" in rewritten
    assert "--to-destination 10.0.0.10:50443" in rewritten
    assert "-d 10.0.0.2/32" in rewritten
    assert "-d 10.0.0.10/32" in rewritten
    assert "10.0.0.20" not in rewritten
    assert "10.0.0.210" not in rewritten


def test_plan_destination_rewrite_builds_iptables_argv():
    plan = plan_destination_rewrite(FIXTURE_NAT_SAVE, "203.0.113.10", "203.0.113.99")
    assert plan, "expected at least one replace command pair"
    # Each step is a list of argv tokens for iptables (no shell).
    for argv in plan:
        assert argv[0] == "iptables"
        assert "-t" in argv and "nat" in argv
        joined = " ".join(argv)
        # Old IP removed from live rules via -D; new via -A / -R
        assert "203.0.113.10" in joined or "203.0.113.99" in joined


def test_plan_rejects_same_ip():
    with pytest.raises(ValueError):
        plan_destination_rewrite(FIXTURE_NAT_SAVE, "203.0.113.10", "203.0.113.10")


def test_plan_rejects_bad_new_ip():
    with pytest.raises(ValueError):
        plan_destination_rewrite(FIXTURE_NAT_SAVE, "203.0.113.10", "not-an-ip")


def test_parse_conntrack_mappings_shape():
    from proxy_agent.conntrack_maps import parse_conntrack_mappings

    sample = (
        "tcp      6 431999 ESTABLISHED src=192.0.2.10 dst=198.51.100.1 sport=40000 dport=443 "
        "src=203.0.113.10 dst=198.51.100.1 sport=50443 dport=40000 [ASSURED] mark=0 use=1\n"
    )
    mappings = parse_conntrack_mappings(sample)
    assert len(mappings) == 1
    m = mappings[0]
    assert m["client_ip"] == "192.0.2.10"
    assert m["client_port"] == 40000
    assert m["proxy_sport"] == 443
    assert m["dest_ip"] == "203.0.113.10"
    assert m["dest_port"] == 50443
    assert parse_conntrack_mappings("") == []


def test_invert_iptables_argv_flips_d_and_a():
    assert invert_iptables_argv(["iptables", "-w", "-t", "nat", "-D", "PREROUTING", "x"]) == [
        "iptables",
        "-w",
        "-t",
        "nat",
        "-A",
        "PREROUTING",
        "x",
    ]
    assert invert_iptables_argv(["iptables", "-A", "POSTROUTING", "y"])[1] == "-D"


def test_apply_iptables_plan_rollbacks_on_mid_failure():
    """On failure of step N, invert and re-run steps 0..N-1 in reverse."""
    plan = [
        ["iptables", "-w", "-t", "nat", "-D", "PREROUTING", "old1"],
        ["iptables", "-w", "-t", "nat", "-A", "PREROUTING", "new1"],
        ["iptables", "-w", "-t", "nat", "-D", "PREROUTING", "old2"],  # fails
        ["iptables", "-w", "-t", "nat", "-A", "PREROUTING", "new2"],
    ]
    calls: list[list[str]] = []

    def fake_run(argv, **_kwargs):
        calls.append(list(argv))
        # Fail the third forward step (index 2)
        if argv == plan[2]:
            return SimpleNamespace(returncode=1, stderr="boom", stdout="")
        return SimpleNamespace(returncode=0, stderr="", stdout="")

    with pytest.raises(IptablesApplyError) as ei:
        apply_iptables_plan(plan, runner=fake_run)

    assert "boom" in str(ei.value)
    # Forward: step0, step1, step2(fail) → rollback invert(step1), invert(step0)
    assert calls[:3] == plan[:3]
    assert calls[3] == invert_iptables_argv(plan[1])  # -A new1 → -D new1
    assert calls[4] == invert_iptables_argv(plan[0])  # -D old1 → -A old1
    assert len(calls) == 5
