"""DNS через WARP: разбор kresd.conf/fallback.lua, счётчики iptables, статус и режимы WARP."""

from __future__ import annotations

from app.services import warp_dns
from app.services.warp_geo import _mode_class

KRESD_CONF = """
local dns1 = 1
local dns2 = 2
local function forward(dns)
	if dns == 1 then
		return policy.FORWARD({'62.76.76.62', '62.76.62.76', '195.208.4.1'})
	elseif dns == 2 then
		-- Cloudflare+Quad9
		return policy.FORWARD({'1.1.1.1', '1.0.0.1', '9.9.9.10', '9.9.9.10@9953'})
	elseif dns == 6 then
		return policy.STUB({'83.220.169.155', '212.109.195.93'})
	else
		panic('Invalid dns value')
	end
end
"""

FALLBACK_LUA = """
local M = {
	layer = {},
	timeout = 2 * sec,
	action = policy.FORWARD({'1.1.1.1', '9.9.9.10@9953', '86.54.11.100'})
}
"""

NAT_SAVE = """# Generated by iptables-save
*nat
:PREROUTING ACCEPT [0:0]
[120:7200] -A PREROUTING -s 10.29.0.0/16 -p udp -m udp --dport 53 -j DNAT --to-destination 127.1.1.1
[3:180] -A PREROUTING -s 10.29.0.0/16 -p tcp -m tcp --dport 53 -j DNAT --to-destination 127.1.1.1
[40:2400] -A PREROUTING -s 10.28.0.0/16 -p udp -m udp --dport 53 -j DNAT --to-destination 127.2.2.2
[9:540] -A PREROUTING -s 10.9.0.0/24 -p udp -m udp --dport 53 -j DNAT --to-destination 127.1.1.1
[77:4620] -A PREROUTING -i eth0 -p udp -m udp --dport 540 -j REDIRECT --to-ports 51443
COMMIT
"""

MANGLE_SAVE = """*mangle
[5:300] -A PREROUTING -s 10.29.0.0/16 ! -d 10.28.0.0/15 -p udp -m udp --dport 53 -m comment --comment az-dns-foreign
[1:60] -A PREROUTING -s 10.29.0.0/16 ! -d 10.28.0.0/15 -p tcp -m tcp --dport 53 -m comment --comment az-dns-foreign
[0:0] -A PREROUTING -s 10.28.0.0/15 -d 198.18.0.0/15 -j ANTIZAPRET-WARP
COMMIT
"""


def test_parse_resolver_sets_and_choice():
    sets = warp_dns.parse_resolver_sets(KRESD_CONF)
    assert sets["1"] == ["62.76.76.62", "62.76.62.76", "195.208.4.1"]
    # порт @9953 отбрасывается, повтор адреса не дублируется
    assert sets["2"] == ["1.1.1.1", "1.0.0.1", "9.9.9.10"]
    assert sets["6"] == ["83.220.169.155", "212.109.195.93"]
    assert warp_dns.parse_dns_choice(KRESD_CONF) == {"dns1": "1", "dns2": "2"}


def test_parse_fallback_resolvers():
    assert warp_dns.parse_fallback_resolvers(FALLBACK_LUA) == ["1.1.1.1", "9.9.9.10", "86.54.11.100"]
    assert warp_dns.parse_fallback_resolvers("") == []


def test_parse_outgoing_reply():
    assert warp_dns.parse_outgoing("> '10.2.0.2'\n> ") == "10.2.0.2"
    assert warp_dns.parse_outgoing("> nil\n> ") is None


def test_parse_dns_counters_groups_by_subnet():
    counters = warp_dns.parse_dns_counters(NAT_SAVE, MANGLE_SAVE)
    intercepted = {row["subnet"]: row for row in counters["intercepted"]}
    assert intercepted["10.29.0.0/16"]["udp"] == 120
    assert intercepted["10.29.0.0/16"]["tcp"] == 3
    assert intercepted["10.29.0.0/16"]["label"] == "AntiZapret VPN"
    assert intercepted["10.28.0.0/16"]["udp"] == 40
    assert intercepted["10.9.0.0/24"]["label"] == "AmneziaWG 3 — AntiZapret"
    # REDIRECT порта VPN к DNS не относится
    assert len(intercepted) == 3
    foreign = {row["subnet"]: row for row in counters["foreign"]}
    # "! -d" не путается с адресом источника
    assert foreign["10.29.0.0/16"] == {
        "subnet": "10.29.0.0/16", "label": "AntiZapret VPN", "udp": 5, "tcp": 1,
    }


def test_foreign_counters_absent_on_old_node_scripts():
    counters = warp_dns.parse_dns_counters(NAT_SAVE, "*mangle\nCOMMIT\n")
    assert counters["foreign"] is None


def test_alternative_client_ip_labels():
    nat = "[1:60] -A PREROUTING -s 172.29.0.0/16 -p udp -m udp --dport 53 -j DNAT --to-destination 127.1.1.1\n"
    rows = warp_dns.parse_dns_counters(nat, "", client_prefix="172")["intercepted"]
    assert rows[0]["label"] == "AntiZapret VPN"


def _status(**kwargs):
    base = dict(enabled=True, warp_active=True, dns2="2", outgoing2="10.2.0.2", kresd2_devs=["warp-antizapret"] * 3)
    base.update(kwargs)
    return warp_dns.evaluate_status(**base)[0]


def test_evaluate_status():
    assert _status() == "ok"
    assert _status(enabled=False) == "off"
    assert _status(warp_active=False) == "no_warp"
    assert _status(dns2="1") == "russian_set"
    assert _status(outgoing2=None, kresd2_devs=["eth0"]) == "leak"
    assert _status(kresd2_devs=["warp-antizapret", "eth0"]) == "leak"


def test_mode_class_ignores_warp_dns_rule():
    # режим 3/4 (правила с fwmark) + правило DNS через WARP для одиночного адреса WARP
    rules = (
        "9990:\tfrom 10.2.0.2 lookup 13335\n"
        "10000:\tfrom 10.29.0.0/16 fwmark 0x2 lookup 13335\n"
        "10000:\tfrom 10.9.0.0/24 fwmark 0x2 lookup 13335\n"
    )
    assert _mode_class(rules, "13335") == "marked"
    assert _mode_class("9990:\tfrom 10.2.0.2 lookup 13335\n", "13335") == "none"
    assert _mode_class("10000:\tfrom 10.29.0.0/16 lookup 13335\n", "13335") == "all"
