#!/bin/bash
# Значения по умолчанию для backend/.env (AdminPanelAZ, синхронизировано с AdminAntizapret 1.9.0)

_ensure_env_default() {
    local key="$1"
    local value="$2"
    local env_file="${ENV_FILE:?ENV_FILE не задан}"

    mkdir -p "$(dirname "$env_file")"
    [ -f "$env_file" ] || touch "$env_file"
    grep -q "^${key}=" "$env_file" 2>/dev/null && return 0
    printf '%s=%s\n' "$key" "$value" >> "$env_file"
}

ensure_env_defaults() {
    _ensure_env_default "TRAFFIC_SYNC_ENABLED" "true"
    _ensure_env_default "TRAFFIC_SYNC_INTERVAL_SECONDS" "60"
    _ensure_env_default "TRAFFIC_LIMIT_RECONCILE_AFTER_SYNC" "true"
    _ensure_env_default "WG_POLICY_SYNC_ENABLED" "true"
    _ensure_env_default "WG_POLICY_SYNC_INTERVAL_SECONDS" "120"
    _ensure_env_default "MONITOR_ENABLED" "true"
    _ensure_env_default "MONITOR_CPU_THRESHOLD" "90"
    _ensure_env_default "MONITOR_RAM_THRESHOLD" "90"
    _ensure_env_default "MONITOR_CHECK_INTERVAL_SECONDS" "60"
    _ensure_env_default "MONITOR_COOLDOWN_MINUTES" "30"
    _ensure_env_default "MONITOR_SUSTAINED_SECONDS" "180"
    _ensure_env_default "CIDR_DB_SOURCE_FETCH_TIMEOUT" "90"
    _ensure_env_default "CIDR_DB_SOURCE_FETCH_RETRIES" "3"
    _ensure_env_default "FEATURE_OPENVPN_ENABLED" "true"
    _ensure_env_default "FEATURE_WIREGUARD_ENABLED" "true"
    _ensure_env_default "FEATURE_AMNEZIAWG_ENABLED" "true"
    _ensure_env_default "FEATURE_LOGS_DASHBOARD_ENABLED" "true"
    _ensure_env_default "FEATURE_SERVER_MONITOR_ENABLED" "true"
    _ensure_env_default "FEATURE_ROUTING_ENABLED" "true"
    _ensure_env_default "FEATURE_WARPER_ENABLED" "true"
    _ensure_env_default "FEATURE_EDIT_FILES_ENABLED" "true"
    _ensure_env_default "FEATURE_TELEGRAM_ENABLED" "true"
    _ensure_env_default "FEATURE_BACKUPS_ENABLED" "true"
    _ensure_env_default "FEATURE_MAINTENANCE_ENABLED" "true"
    _ensure_env_default "FEATURE_SECURITY_ENABLED" "true"
    _ensure_env_default "FEATURE_DIAGNOSTICS_TESTS_ENABLED" "true"
    _ensure_env_default "FEATURE_USER_MANAGEMENT_ENABLED" "true"
    _ensure_env_default "FEATURE_ACTION_LOGS_ENABLED" "true"
    _ensure_env_default "FEATURE_SYSTEM_UPDATES_ENABLED" "true"
    _ensure_env_default "FEATURE_QR_DOWNLOADS_ENABLED" "true"
    _ensure_env_default "FEATURE_VPN_NETWORK_ENABLED" "true"
    _ensure_env_default "ACTIVE_WEB_SESSION_TRACKING_ENABLED" "true"
    _ensure_env_default "ACTIVE_WEB_SESSION_TTL_SECONDS" "180"
    _ensure_env_default "ACTIVE_WEB_SESSION_TOUCH_INTERVAL_SECONDS" "30"
    _ensure_env_default "NIGHTLY_IDLE_RESTART_ENABLED" "true"
    _ensure_env_default "NIGHTLY_IDLE_RESTART_CRON" "0 4 * * *"
    _ensure_env_default "RUNTIME_BACKUP_CLEANUP_ENABLED" "true"
    _ensure_env_default "ADMIN_PANEL_AZ_SERVICE_NAME" "adminpanelaz"
    # Публикация (nginx-setup.sh задаёт DOMAIN, BEHIND_NGINX, TRUSTED_PROXY_IPS)
    _ensure_env_default "BEHIND_NGINX" "false"
    _ensure_env_default "CLOUDFLARE_PROXY_ENABLED" "true"
    _ensure_env_default "CLOUDFLARE_IPS_AUTO_UPDATE" "false"
    _ensure_env_default "CLOUDFLARE_IPS_UPDATE_INTERVAL_DAYS" "7"
    _ensure_env_default "APP_ENV" "development"
    _ensure_env_default "AUTH_RATE_LIMIT_ENABLED" "true"
    _ensure_env_default "API_RATE_LIMIT_ENABLED" "true"
    _ensure_env_default "API_RATE_LIMIT_MAX_REQUESTS" "120"
    _ensure_env_default "API_RATE_LIMIT_WINDOW_SECONDS" "60"
    _ensure_env_default "API_RATE_LIMIT_BACKEND" "memory"
    _ensure_env_default "SECURITY_HEADERS_ENABLED" "true"
    _ensure_env_default "AUDIT_LOG_ENABLED" "true"
    _ensure_env_default "LOCAL_ANTIZAPRET_ENABLED" "true"
}
